version: '3'

services:
  sansu:
    container_name: sansu
    build:
      context: .
    image: "sansu:0.0.1"
    restart: always
    volumes:
      - ./modelscope_cache:/mnt/workspace/.cache/modelscope
    ports:
      - ${PORT}:${PORT}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
